# Generated by Django 3.2.4 on 2021-06-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210629_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('select', 'choose'), ('M', 'Male'), ('F', 'Female')], default='select', max_length=50),
        ),
    ]
